apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythoapp
  labels:
    app: pythoapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythoapp
  template:
    metadata:
      labels:
        app: pythoapp
    spec:
      containers:
        - name: pythoapp
          image: azaksacr1.azurecr.io/image-workflow-1692317808077:latest
          ports:
            - containerPort: 8000