apiVersion: v1
kind: Service
metadata:
  name: pythoapp
  namespace: namespace-workflow-1692317075869
spec:
  type: LoadBalancer
  selector:
    app: pythoapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000